### ISSUE TITLE
Token validation should also validate JWT with public key

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/ego-token-utils#11]
**Problem**
Currently, the `isValidToken` function does not validate JWT authenticity, the library does not know anything about the public key

**Solution**
The library's default export needs to be updated to a "constructor" function that looks like so:
```javascript
import jwt from 'jsonwebtoken';

export default (egoPublicKey: string) => ({
  isValidToken: (token) => {
    jwt.verify(token, key)
    ...
  }
  ...
})
```

Note: this introduces a breaking change so platform's UI needs to be updated to handle this change

**Comment by rosibaj** [comment]
Tested the QA platform today - looks like everything is authenticating correctly based on role so closing ticket as QA has passed!
